stages:
  - build
  - deploy
  
build-dev:
  image: docker:latest
  stage: build
  script:
    - pwd
    - cd /builds/rukamir/codemule-server
    - docker build -t codemule .
    - docker save codemule > /tmp/codemule.tar
  artifacts:
    paths:
      - /tmp/codemule.tar
    expire_in: 1 week

deploy-aws:
  image: python:latest
  stage: deploy
  script:
    - docker images
    - pip install awscli --upgrade --user